---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    p, role:argocd-admin, applications, get, */*, allow
    p, role:argocd-admin, applications, sync, */*, allow
    p, role:argocd-admin, applications, update, */*, allow
    p, role:argocd-admin, applications, override, */*, allow
    p, role:argocd-admin, applications, action/apps/*/restart, */*, allow
    p, role:argocd-admin, applications, action/batch/*/create-job, */*, allow
    p, role:argocd-admin, clusters, get, *, allow
    p, role:argocd-admin, repositories, get, *, allow
    p, role:argocd-admin, logs, get, *, allow
    p, role:argocd-admin, exec, create, */*, allow
    p, role:argocd-admin, projects, get, */*, allow
    g, argocd-admins, role:argocd-admin
  policy.default: role:readonly
  scopes: [groups]
