---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
data:
  admin.password: JDJhJDEwJEE5Z29kZVdxWUxXVTE4OUFLTHpncE92N0xFRVVicDBOb2V6WG9xVWk5N3pxRi82WlBRaXFt
  admin.passwordMtime: MjAyNC0wOC0xNlQxNzowNzoyOENFU1Q=
