---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd-server.argocd.svc.cluster.local
  kustomize.buildOptions: --enable-helm --load-restrictor LoadRestrictionsNone
  application.instanceLabelKey: argocd.argoproj.io/instance
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
    jsonPointers:
    - /webhooks/0/namespaceSelector/matchExpressions
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    - type: saml
      id: okta
      name: Okta
      config:
        ssoURL: $okta-secret:sso-url
        caData: $okta-secret:sso-cer
        usernameAttr: email
        emailAttr: email
        groupsAttr: group
    staticClients:
      - id: argo-workflows-sso
        name: Argo Workflow
        redirectURIs:
          - https://argo-workflows.imjoseangel.eu.org/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
