---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: argocd-server
          env:
          - name: ARGOCD_API_SERVER_REPLICAS
            value: "1"
          - name: GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: argocd-secret
                key: github.clientId
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: argocd-secret
                key: github.clientSecret
