---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    p, role:admin, applications, get, */*, allow
    p, role:admin, applications, sync, */*, allow
    p, role:admin, applications, update, */*, allow
    p, role:admin, applications, override, */*, allow
    p, role:admin, applications, action/apps/*/restart, */*, allow
    p, role:admin, applications, action/batch/*/create-job, */*, allow
    p, role:admin, clusters, get, *, allow
    p, role:admin, repositories, get, *, allow
    p, role:admin, logs, get, *, allow
    p, role:admin, exec, create, */*, allow
    p, role:admin, projects, get, */*, allow
    g, admins, role:admin
  policy.default: role:readonly
  scopes: '[email,groups]'
