---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: coredns
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: coredns
    spec:
      destination:
        name: "{{cluster}}"
        namespace: kube-system
      project: default
      source:
        path: coredns
        repoURL: https://github.com/imjoseangel/k8s-gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
