---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: argocd
    repoURL: git@ssh.dev.azure.com:v3/example/ops-k8s-deployments/k8s-core-base
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
