---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudflare-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - list:
      elements:
        - cluster: in-cluster
  template:
    metadata:
      name: "cloudflare-crds"
    spec:
      destination:
        name: "{{cluster}}"
      project: external
      source:
        path: deploy/crds
        repoURL: https://github.com/cloudflare/origin-ca-issuer.git
        targetRevision: HEAD
        directory:
          recurse: true
      syncPolicy:
        syncOptions:
          - Replace=true
        automated:
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudflare-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - list:
      elements:
        - cluster: in-cluster
  template:
    metadata:
      name: "cloudflare-rbac"
    spec:
      destination:
        name: "{{cluster}}"
      project: external
      source:
        path: deploy/rbac
        repoURL: https://github.com/cloudflare/origin-ca-issuer.git
        targetRevision: HEAD
        directory:
          recurse: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudflare
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - list:
      elements:
        - cluster: in-cluster
  template:
    metadata:
      name: "cloudflare"
    spec:
      destination:
        name: "{{cluster}}"
      project: external
      source:
        path: deploy/manifests
        repoURL: https://github.com/cloudflare/origin-ca-issuer.git
        targetRevision: HEAD
        directory:
          recurse: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
