---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argoworkflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - list:
      elements:
        - cluster: in-cluster
  template:
    metadata:
      name: "argoworkflow"
    spec:
      destination:
        name: "{{cluster}}"
      project: default
      source:
        path: argoworkflow
        repoURL: https://github.com/imjoseangel/k8s-gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argoevents
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - list:
      elements:
        - cluster: in-cluster
  template:
    metadata:
      name: "argoevents"
    spec:
      destination:
        name: "{{cluster}}"
      project: default
      source:
        path: argoevents
        repoURL: https://github.com/imjoseangel/k8s-gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
