---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd.imjoseangel.eu.org
  namespace: argocd
spec:
  secretName: ingress-tls
  dnsNames:
    - argocd.imjoseangel.eu.org
  duration: 168h
  renewBefore: 24h
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: origin-ca-issuer
