---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudprober-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "cloudflare-issuer"
    acme.cert-manager.io/dns01-provider: cloudflare
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: cloudprober
                port:
                  number: 9313
      host: cloudprober.imjoseangel.eu.org
  tls:
    - hosts:
      - cloudprober.imjoseangel.eu.org
      secretName: ingress-tls
