---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-workflows
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - list:
      elements:
        - cluster: in-cluster
  template:
    metadata:
      name: "argo-workflows"
    spec:
      destination:
        name: "{{cluster}}"
      project: default
      source:
        path: argo-workflows
        repoURL: https://github.com/imjoseangel/k8s-gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-events
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - list:
      elements:
        - cluster: in-cluster
  template:
    metadata:
      name: "argo-events"
    spec:
      destination:
        name: "{{cluster}}"
      project: default
      source:
        path: argo-events
        repoURL: https://github.com/imjoseangel/k8s-gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
