---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: argocd
    spec:
      destination:
        name: "{{cluster}}"
        namespace: argocd
      project: default
      source:
        path: argocd
        repoURL: https://github.com/imjoseangel/k8s-gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-projects
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: argocd-projects
    spec:
      destination:
        name: "{{cluster}}"
        namespace: argocd
      project: default
      source:
        path: argocd-resources/projects
        repoURL: https://github.com/imjoseangel/k8s-gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-applications
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: argocd-applications
    spec:
      destination:
        name: "{{cluster}}"
        namespace: argocd
      project: default
      source:
        path: argocd-resources/applications
        repoURL: https://github.com/imjoseangel/k8s-gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
