apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-reader-user
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin-user
  annotations:
    workflows.argoproj.io/rbac-rule: "'a960123f-974c-4d67-b12f-1592b9137206' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-executor
  annotations:
    azure.workload.identity/client-id: ~
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-admin-user.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo-admin-user
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-reader-user.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo-reader-user
type: kubernetes.io/service-account-token
---
