---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # argocd
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

  # base
  - base

  # configuration
  - configuration

  # resources
  - resources

patches:
  - path: patches/argocd-application-controller.yaml
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-cmd-params-cm.yaml
  - path: patches/argocd-dex-server.yaml
  - path: patches/argocd-rbac-cm.yaml
  - path: patches/argocd-repo-server.yaml
  - path: patches/argocd-server.yaml
  - path: patches/argocd-service.yaml
