---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso
data:
  # client-id is 'my-client-id-1234-1234'
  client-id: bXktY2xpZW50LWlkLTEyMzQtMTIzNAo=
  # client-secret is 'my-client-secret-very-secret'
  client-secret: bXktY2xpZW50LXNlY3JldC12ZXJ5LXNlY3JldAo=
