---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso
data:
  # client-id is 'argo-workflows-sso'
  client-id: YXJnby13b3JrZmxvd3Mtc3Nv
  # client-secret is 'cc217ae4-5425-412b-abd0-074332b64373'
  client-secret: Y2MyMTdhZTQtNTQyNS00MTJiLWFiZDAtMDc0MzMyYjY0Mzcz
