---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows

resources:
- https://github.com/argoproj/argo-workflows/releases/latest/download/install.yaml
- argo-workflows-controller-pdb.yaml
- argo-workflows-sso.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- ingress.yaml
- namespace.yaml
- serviceaccount.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argo-server
        namespace: argo
      spec:
        template:
          spec:
            containers:
              - name: argo-server
                args:
                  - server
