---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows

resources:
- https://github.com/argoproj/argo-workflows/releases/latest/download/install.yaml
- resources

patches:
  - path: patches/argo-server.yaml
  - path: patches/workflow-controller-configmap.yaml
