apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-reader-user
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin-user
  annotations:
    workflows.argoproj.io/rbac-rule: "'argo-workflows-admins' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-executor
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-admin-user.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo-admin-user
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-reader-user.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo-reader-user
type: kubernetes.io/service-account-token
---
