---
helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.11.1
    releaseName: ingress-nginx
    namespace: ingress-nginx
    valuesFile: values.yaml
