---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
  - resources

patches:
  - path: patches/cert-manager.yaml
