---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - https://github.com/cloudflare/origin-ca-issuer.git
