---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tls-issuer
  namespace: argocd
spec:
  acme:
    email: josea.munoz@gmail.com
#    server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
